services:
  - type: web
    name: gutenberg-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: FLASK_APP
        value: models.py
    buildEnv:
      - key: PYTHON_VERSION
        value: 3.9.16

databases:
  - name: gutenberg-db
    databaseName: gutenberg
    user: gutenberg_user
    plan: free

