services:
  - type: web
    name: gutenberg-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app --timeout 60
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
    buildEnv:
      - key: PYTHON_VERSION
        value: 3.9.16

databases:
  - name: gutenberg-db
    databaseName: gutenberg
    user: gutenberg_user
    plan: free

